### ISSUE TITLE
Some questions on the implementation of fastv_kvcache.py

### ISSUE THREAD

**Issue by momo6-bit** [pkunlp-icler/FastV#18]
Hi! Thanks for your great contribution to the community!

I have some questions on the implementation of `fastv_kvcache.py`
1. I notice that [this part](https://github.com/pkunlp-icler/FastV/blob/cf91d095a99e7dfdaf82df0ab49966646c6efa27/src/FastV/lmms-eval/fastv_kvcache.py#L134) will lead the kv cache in k-th layer has a double length and it seems to be duplicated content, which might result in unexpected outcomes.

2. When I'm trying to evaluate with `lmms-eval` with `K=1, ratio=0.5`. The cmd is as followed
```
accelerate launch  --num_processes=1 --main_process_port=12345 -m lmms_eval --model llava \
    --model_args pretrained="liuhaotian/llava-v1.5-7b"  \
    --tasks textvqa_val --batch_size 1 \
    --log_samples_suffix 7b_fastv \
    --output_path ./logs/7b/textvqa_val
```
The error is raised in the first sample.
```
Traceback (most recent call last):
  File "/data2/workspace/my_FastV/lmms-evaluation/lmms_eval/__main__.py", line 206, in cli_evaluate
    results, samples = cli_evaluate_single(args)
  File "/data2/workspace/my_FastV/lmms-evaluation/lmms_eval/__main__.py", line 301, in cli_evaluate_single
    results = evaluator.simple_evaluate(
  File "/data2/workspace/my_FastV/lmms-evaluation/lmms_eval/utils.py", line 453, in _wrapper
    return fn(*args, **kwargs)
  File "/data2/workspace/my_FastV/lmms-evaluation/lmms_eval/evaluator.py", line 135, in simple_evaluate
    results = evaluate(
  File "/data2/workspace/my_FastV/lmms-evaluation/lmms_eval/utils.py", line 453, in _wrapper
    return fn(*args, **kwargs)
  File "/data2/workspace/my_FastV/lmms-evaluation/lmms_eval/evaluator.py", line 297, in evaluate
    resps = getattr(lm, reqtype)(cloned_reqs)  # Choiszt run generate until
  File "/data2/workspace/my_FastV/lmms-evaluation/lmms_eval/models/llava.py", line 407, in generate_until
    raise e
  File "/data2/workspace/my_FastV/lmms-evaluation/lmms_eval/models/llava.py", line 392, in generate_until
    cont = self.model.generate(
  File "/data2/miniconda3/envs/fastv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/data2/workspace/my_FastV/llava/model/language_model/llava_llama.py", line 138, in generate
    return super().generate(
  File "/data2/miniconda3/envs/fastv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/data2/miniconda3/envs/fastv/lib/python3.10/site-packages/transformers/generation/utils.py", line 1479, in generate
    return self.greedy_search(
  File "/data2/miniconda3/envs/fastv/lib/python3.10/site-packages/transformers/generation/utils.py", line 2340, in greedy_search
    outputs = self(
  File "/data2/miniconda3/envs/fastv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data2/miniconda3/envs/fastv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data2/workspace/my_FastV/llava/model/language_model/llava_llama.py", line 92, in forward
    return super().forward(
  File "/data2/miniconda3/envs/fastv/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 1183, in forward
    outputs = self.model(
  File "/data2/miniconda3/envs/fastv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data2/miniconda3/envs/fastv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data2/workspace/my_FastV/llava/model/language_model/fastv_kvcache.py", line 141, in forward
    temp_layer_outputs = decoder_layer(
  File "/data2/miniconda3/envs/fastv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data2/miniconda3/envs/fastv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data2/miniconda3/envs/fastv/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 798, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/data2/miniconda3/envs/fastv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data2/miniconda3/envs/fastv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data2/miniconda3/envs/fastv/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 682, in forward
    return super().forward(
  File "/data2/miniconda3/envs/fastv/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 404, in forward
    query_states, key_states = apply_rotary_pos_emb(query_states, key_states, cos, sin, position_ids)
  File "/data2/miniconda3/envs/fastv/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 234, in apply_rotary_pos_emb
    q_embed = (q * cos) + (rotate_half(q) * sin)
RuntimeError: The size of tensor a (0) must match the size of tensor b (671) at non-singleton dimension 2
```
And I find that in the second forward, `input_ids` to `LlamaModel` is an empty tensor `[]`. I don't know whether it relates to the first question.
 
Do you have any ideas?

I really appreciate any help you can provide.

**Comment by momo6-bit** [comment]
Mine is 0.2.0.dev0 version. And now I've already figured out that this implementation is a compromise to the `SdpaAttention` in `transformers`.

**Comment by Naive-Bayes** [comment]
> Mine is 0.2.0.dev0 version. And now I've already figured out that this implementation is a compromise to the `SdpaAttention` in `transformers`.

I also met this problem, could you tell me how to solve it? Just change lmms_eval version to 0.1.1?
