### ISSUE TITLE
The tokenizer can not be loaded.

### ISSUE THREAD

**Issue by wkfdb** [pkunlp-icler/FastV#36]
I create the environment following 

conda create -n fastv-hf python=3.10
conda activate fastv-hf
cd ./src/FastV/llava-hf/transformers
pip install -e .
pip install pillow torch accelerate

and download the "llava-hf/llava-1.5-13b-hf" from huggingface, and change the model_id in demo_hf.py to my saving path.

The model loaded successfully, however when loading the tokenzier, the following error occurs:

Traceback (most recent call last):
  File "/mnt/data/group/wangkuo/FastV-main/demo-hf.py", line 31, in <module>
    processor = AutoProcessor.from_pretrained(model_id) # always fails at this line
  File "/mnt/data/group/wangkuo/FastV-main/src/FastV/llava-hf/transformers/src/transformers/models/auto/processing_auto.py", line 312, in from_pretrained
    return processor_class.from_pretrained(
  File "/mnt/data/group/wangkuo/FastV-main/src/FastV/llava-hf/transformers/src/transformers/processing_utils.py", line 465, in from_pretrained
    args = cls._get_arguments_from_pretrained(pretrained_model_name_or_path, **kwargs)
  File "/mnt/data/group/wangkuo/FastV-main/src/FastV/llava-hf/transformers/src/transformers/processing_utils.py", line 511, in _get_arguments_from_pretrained
    args.append(attribute_class.from_pretrained(pretrained_model_name_or_path, **kwargs))
  File "/mnt/data/group/wangkuo/FastV-main/src/FastV/llava-hf/transformers/src/transformers/tokenization_utils_base.py", line 2086, in from_pretrained
    return cls._from_pretrained(
  File "/mnt/data/group/wangkuo/FastV-main/src/FastV/llava-hf/transformers/src/transformers/tokenization_utils_base.py", line 2325, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/mnt/data/group/wangkuo/FastV-main/src/FastV/llava-hf/transformers/src/transformers/models/llama/tokenization_llama_fast.py", line 133, in __init__
    super().__init__(
  File "/mnt/data/group/wangkuo/FastV-main/src/FastV/llava-hf/transformers/src/transformers/tokenization_utils_fast.py", line 111, in __init__
    fast_tokenizer = TokenizerFast.from_file(fast_tokenizer_file)
Exception: data did not match any variant of untagged enum ModelWrapper at line 277156 column 3

Any clues for solving this problem?

**Comment by wkfdb** [comment]
It seems that the llava-hf needs tokenizers>=0.20, and no longer supports the older versions. The transformers version in your src code is 4.39.0.dev0 and it need tokenizers>=0.14, <0.19, which is conflict with the above llava-hf requirement.

**Comment by MiloQ** [comment]
Hello,

I encountered the same issue. How did you eventually resolve it?

**Comment by wkfdb** [comment]
Still not solved. I just made a re-implementation on other MLLMs according to the code.

**Comment by HaozheZhao** [comment]
Hi,  @wkfdb @MiloQ 

The issue arises due to the update of the processor for the **llava-hf** models in November. Here are the relevant commits for reference:  

- [Update for llava-1.5-7b-hf](https://huggingface.co/llava-hf/llava-1.5-7b-hf/commit/ca4bea31bcbe6d887effc1aa34957161566f7033)  
- [Update for llava-1.5-13b-hf](https://huggingface.co/llava-hf/llava-1.5-13b-hf/commit/d14477508557f73c8fee5f7f9497e13cdfd41129)  

These updates introduced a dependency on a newer version of the tokenizer, which conflicts with the version of the Transformers library we are using.  

To avoid this issue, I recommend loading an earlier revision of the model and tokenizer by specifying the `revision` argument.  

Here’s an example:  

```python
from transformers import LlavaForConditionalGeneration, AutoProcessor

model_id = "llava-hf/llava-1.5-13b-hf"
revision = "0fad4a3"  # Use "a272c74" for llava-1.5-7b-hf

fastv_config = {
    "use_fastv": True,
    "fastv_k": 3,
    "fastv_r": 0.75,
    "image_token_start_index": 5, 
    "image_token_length": 576
}

model = LlavaForConditionalGeneration.from_pretrained(
    model_id, 
    revision=revision,
    torch_dtype=torch.float16, 
    low_cpu_mem_usage=True, 
    attn_implementation="eager",
    fastv_config=fastv_config  # Comment this line to use vanilla decoding
).to(0)

processor = AutoProcessor.from_pretrained(
    model_id,
    revision=revision
)
```  

Using the `revision` argument ensures compatibility with the Transformers version you're working with. Let me know if this resolves your issue!
